// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkueqzksxzfvffflgvnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrdWVxemtzeHpmdmZmZmxndm50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTQzNTMsImV4cCI6MjA2NjI3MDM1M30.t_FSmEcQ64y2wjsggfzJCLXDTVSAT0slrE6Aevl3bcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);